module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'revert',
        'ci',
        'build',
      ],
    ],
    // Warn on unknown scopes (do not block commits — matches backend commitlint policy).
    'scope-enum': [
      1,
      'always',
      [
        'web',
        'admin',
        'landing',
        'ui',
        'api-client',
        'openapi',
        'websocket',
        'auth',
        'types',
        'utils',
        'config',
        'constants',
        'validators',
        'hooks',
        'field-help',
        'auth-feature',
        'projects',
        'requests',
        'quotes',
        'messaging',
        'notifications',
        'payments',
        'media',
        'portfolio',
        'profile',
        'dashboard',
        'docker',
        'scripts',
        'repo',
        'root',
        'deps',
        'release',
      ],
    ],
    'scope-case': [2, 'always', 'lower-case'],
    'subject-max-length': [2, 'always', 100],
    'body-max-line-length': [1, 'always', 200],
  },
};
