export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  dashboard: '/dashboard',
  projects: '/projects',
  project: (id: string) => `/projects/${id}` as const,
  projectNew: '/projects/new',
  requests: '/requests',
  request: (id: string) => `/requests/${id}` as const,
  requestNew: '/requests/new',
  quotes: '/quotes',
  quote: (id: string) => `/quotes/${id}` as const,
  messages: '/messages',
  messagesInbox: '/messages/inbox',
  conversation: (id: string) => `/messages/${id}` as const,
  messageThread: (threadId: string) => `/messages/thread/${threadId}` as const,
  messageNewDirect: '/messages/new/direct',
  notifications: '/notifications',
  payments: '/payments',
  paymentMethods: '/payments/methods',
  payment: (id: string) => `/payments/${id}` as const,
  invoices: '/invoices',
  invoice: (id: string) => `/payments/invoice/${id}` as const,
  invoiceDetail: (id: string) => `/payments/invoice/${id}` as const,
  verifyDocument: '/verify-document',
  portfolio: '/portfolio',
  portfolioItem: (id: string) => `/portfolio/${id}` as const,
  profile: '/profile',
  profileEdit: '/profile/edit',
  settings: '/settings',
  settingsAccount: '/settings/account',
  settingsSecurity: '/settings/security',
  settingsNotifications: '/settings/notifications',
  settingsFiles: '/settings/files',
  settingsActivity: '/settings/activity',
  settingsBilling: '/settings/billing',
  settingsSessions: '/settings/sessions',
  contact: '/contact',
  blog: '/blog',
  blogBookmarks: '/blog/bookmarks',
  blogPost: (slug: string) => `/blog/${slug}` as const,
} as const;
