/** Admin API paths (base: `/api/v1`). Grouped for operator reference. */

export type AdminEndpoint = {
  method: 'GET' | 'POST' | 'PATCH' | 'DELETE';
  path: string;
  summary: string;
};

export type AdminEndpointGroup = {
  id: string;
  title: string;
  description: string;
  endpoints: AdminEndpoint[];
};

export const ADMIN_ENDPOINT_GROUPS: AdminEndpointGroup[] = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    description: 'Platform KPIs, revenue, activity, and alerts.',
    endpoints: [
      { method: 'GET', path: '/admin/dashboard/overview', summary: 'Overview KPIs' },
      { method: 'GET', path: '/admin/dashboard/revenue', summary: 'Revenue analytics' },
      { method: 'GET', path: '/admin/dashboard/users', summary: 'User metrics' },
      { method: 'GET', path: '/admin/dashboard/projects', summary: 'Project metrics' },
      { method: 'GET', path: '/admin/dashboard/performance', summary: 'Performance metrics' },
      { method: 'GET', path: '/admin/dashboard/activity', summary: 'Recent activity feed' },
      { method: 'GET', path: '/admin/dashboard/alerts', summary: 'System alerts' },
      { method: 'GET', path: '/admin/health', summary: 'Service health' },
    ],
  },
  {
    id: 'contact',
    title: 'Inquiries',
    description: 'Public contact form submissions before they become service requests.',
    endpoints: [
      { method: 'GET', path: '/admin/contact', summary: 'List inquiries' },
      { method: 'GET', path: '/admin/contact/:id', summary: 'Inquiry detail' },
      { method: 'PATCH', path: '/admin/contact/:id/status', summary: 'Update status' },
      { method: 'POST', path: '/admin/contact/:id/respond', summary: 'Send response' },
      { method: 'POST', path: '/admin/contact/:id/spam', summary: 'Mark spam' },
      { method: 'DELETE', path: '/admin/contact/:id', summary: 'Delete inquiry' },
    ],
  },
  {
    id: 'requests',
    title: 'Requests',
    description: 'Client service requests — triage, assign, quote, and close.',
    endpoints: [
      { method: 'GET', path: '/admin/requests', summary: 'List requests' },
      { method: 'GET', path: '/admin/requests/stats', summary: 'Request statistics' },
      { method: 'GET', path: '/admin/requests/:id', summary: 'Request detail' },
      { method: 'PATCH', path: '/admin/requests/:id', summary: 'Update request' },
      { method: 'PATCH', path: '/admin/requests/:id/status', summary: 'Change status' },
      { method: 'POST', path: '/admin/requests/:id/assign', summary: 'Assign operator' },
      { method: 'POST', path: '/admin/requests/:id/quotes', summary: 'Create quote from request' },
      { method: 'GET', path: '/admin/requests/:id/notes', summary: 'List internal notes' },
      { method: 'POST', path: '/admin/requests/:id/notes', summary: 'Add internal note' },
      {
        method: 'GET',
        path: '/admin/requests/:id/attachments/:attachmentId/download',
        summary: 'Download attachment',
      },
      { method: 'DELETE', path: '/admin/requests/:id', summary: 'Delete request' },
    ],
  },
  {
    id: 'quotes',
    title: 'Quotes',
    description: 'Pricing proposals linked to requests; send, revise, and track acceptance.',
    endpoints: [
      { method: 'GET', path: '/admin/quotes', summary: 'List quotes' },
      { method: 'GET', path: '/admin/quotes/stats', summary: 'Quote statistics' },
      { method: 'POST', path: '/admin/quotes', summary: 'Create quote' },
      { method: 'GET', path: '/admin/quotes/:id', summary: 'Quote detail' },
      { method: 'PATCH', path: '/admin/quotes/:id', summary: 'Update quote' },
      { method: 'POST', path: '/admin/quotes/:id/send', summary: 'Send to client' },
      { method: 'POST', path: '/admin/quotes/:id/resend', summary: 'Resend quote' },
      { method: 'DELETE', path: '/admin/quotes/:id', summary: 'Delete quote' },
      { method: 'GET', path: '/admin/quotes/templates', summary: 'Quote templates' },
      { method: 'POST', path: '/admin/quotes/templates', summary: 'Create template' },
    ],
  },
  {
    id: 'projects',
    title: 'Projects',
    description: 'Active work after quote acceptance — status, milestones, deliverables, progress.',
    endpoints: [
      { method: 'GET', path: '/admin/projects', summary: 'List projects' },
      { method: 'GET', path: '/admin/projects/stats', summary: 'Project statistics' },
      { method: 'GET', path: '/admin/projects/:id', summary: 'Project detail' },
      { method: 'PATCH', path: '/admin/projects/:id', summary: 'Update project' },
      { method: 'PATCH', path: '/admin/projects/:id/status', summary: 'Change status' },
      { method: 'POST', path: '/admin/projects/:id/archive', summary: 'Archive' },
      { method: 'POST', path: '/admin/projects/:id/unarchive', summary: 'Unarchive' },
      { method: 'POST', path: '/admin/projects/:id/duplicate', summary: 'Duplicate' },
      { method: 'POST', path: '/admin/projects/:id/export', summary: 'Export data' },
      { method: 'GET', path: '/admin/projects/:id/deliverables', summary: 'List deliverables' },
      { method: 'POST', path: '/admin/projects/:id/deliverables', summary: 'Upload deliverable' },
      { method: 'POST', path: '/admin/projects/:id/milestones', summary: 'Create milestone' },
      { method: 'PATCH', path: '/admin/milestones/:id', summary: 'Update milestone' },
      { method: 'POST', path: '/admin/milestones/:id/complete', summary: 'Complete milestone' },
      { method: 'PATCH', path: '/admin/deliverables/:id', summary: 'Update deliverable' },
      { method: 'DELETE', path: '/admin/deliverables/:id', summary: 'Delete deliverable' },
      { method: 'GET', path: '/admin/progress/projects/:id', summary: 'Progress entries' },
      { method: 'POST', path: '/admin/progress/projects/:id', summary: 'Add progress entry' },
      {
        method: 'GET',
        path: '/admin/progress/projects/:id/timeline',
        summary: 'Progress timeline',
      },
      {
        method: 'POST',
        path: '/admin/progress/projects/:id/complete',
        summary: 'Mark project complete',
      },
    ],
  },
  {
    id: 'payments',
    title: 'Payments',
    description: 'Milestones, refunds, disputes, and reconciliation.',
    endpoints: [
      { method: 'GET', path: '/admin/payments', summary: 'List payments' },
      { method: 'GET', path: '/admin/payments/:id', summary: 'Payment detail' },
      { method: 'POST', path: '/admin/payments/:id/refund', summary: 'Process refund' },
      { method: 'POST', path: '/admin/payments/:id/verify', summary: 'Verify payment' },
      {
        method: 'POST',
        path: '/admin/payments/:id/approve-transfer',
        summary: 'Approve offline bank/UPI transfer',
      },
      {
        method: 'POST',
        path: '/admin/payments/:id/reject-transfer',
        summary: 'Reject offline bank/UPI transfer',
      },
      {
        method: 'GET',
        path: '/admin/payments/accounts',
        summary: 'List platform settlement accounts',
      },
      {
        method: 'POST',
        path: '/admin/payments/accounts',
        summary: 'Create platform settlement account',
      },
      { method: 'GET', path: '/admin/payments/milestones', summary: 'Milestone payments' },
      { method: 'GET', path: '/admin/payments/milestones/:id', summary: 'Milestone detail' },
      {
        method: 'PATCH',
        path: '/admin/payments/milestones/:id',
        summary: 'Update milestone payment',
      },
      {
        method: 'POST',
        path: '/admin/payments/milestones/:id/request-payment',
        summary: 'Request payment',
      },
      {
        method: 'POST',
        path: '/admin/payments/projects/:projectId/milestones',
        summary: 'Create payment milestones',
      },
      { method: 'GET', path: '/admin/payments/disputes/:id', summary: 'Dispute detail' },
      {
        method: 'POST',
        path: '/admin/payments/disputes/:id/respond',
        summary: 'Respond to dispute',
      },
      { method: 'GET', path: '/admin/payments/reconciliation', summary: 'Reconciliation report' },
    ],
  },
  {
    id: 'messages',
    title: 'Messages',
    description: 'Operator messaging and flagged content moderation.',
    endpoints: [
      {
        method: 'POST',
        path: '/admin/messages/projects/:projectId/system',
        summary: 'Broadcast system message',
      },
      { method: 'GET', path: '/admin/messages/flagged', summary: 'Flagged messages' },
      { method: 'POST', path: '/admin/messages/:id/flag', summary: 'Flag a message' },
      { method: 'POST', path: '/admin/messages/flagged/:id/dismiss', summary: 'Dismiss flag' },
      { method: 'POST', path: '/admin/messages/flagged/:id/escalate', summary: 'Escalate flag' },
      { method: 'DELETE', path: '/admin/messages/flagged/:id', summary: 'Remove flagged message' },
    ],
  },
  {
    id: 'users',
    title: 'Users',
    description: 'Client and operator accounts — roles, sessions, impersonation, export.',
    endpoints: [
      { method: 'GET', path: '/admin/users', summary: 'List users' },
      { method: 'GET', path: '/admin/users/search', summary: 'Search users' },
      { method: 'GET', path: '/admin/users/:id', summary: 'User detail' },
      { method: 'PATCH', path: '/admin/users/:id', summary: 'Update profile' },
      { method: 'PATCH', path: '/admin/users/:id/role', summary: 'Change role' },
      { method: 'PATCH', path: '/admin/users/:id/status', summary: 'Suspend / activate' },
      { method: 'DELETE', path: '/admin/users/:id', summary: 'Delete user' },
      { method: 'POST', path: '/admin/users/bulk', summary: 'Bulk operations' },
      { method: 'GET', path: '/admin/users/:id/sessions', summary: 'Active sessions' },
      { method: 'DELETE', path: '/admin/users/sessions/:sessionId', summary: 'Terminate session' },
      {
        method: 'POST',
        path: '/admin/users/:id/terminate-all-sessions',
        summary: 'Terminate all sessions',
      },
      { method: 'GET', path: '/admin/users/:id/activity', summary: 'User activity log' },
      { method: 'POST', path: '/admin/users/:id/export', summary: 'Export user data' },
      { method: 'POST', path: '/admin/users/:id/impersonate', summary: 'Start impersonation' },
      { method: 'POST', path: '/admin/users/:id/restore', summary: 'Restore deleted user' },
      {
        method: 'POST',
        path: '/admin/users/:id/force-password-reset',
        summary: 'Force password reset',
      },
      { method: 'POST', path: '/admin/users/:id/reset-password', summary: 'Set new password' },
      { method: 'GET', path: '/admin/users/logs', summary: 'Admin action logs' },
      { method: 'GET', path: '/admin/users/security-stats', summary: 'User security stats' },
      { method: 'GET', path: '/admin/impersonate/sessions', summary: 'Impersonation sessions' },
      { method: 'POST', path: '/admin/impersonate/end', summary: 'End impersonation' },
    ],
  },
  {
    id: 'content',
    title: 'Blog',
    description: 'Blog posts, comments, tags, and analytics.',
    endpoints: [
      { method: 'GET', path: '/admin/posts', summary: 'List posts' },
      { method: 'POST', path: '/admin/posts', summary: 'Create post' },
      { method: 'GET', path: '/admin/posts/:id', summary: 'Post detail' },
      { method: 'PATCH', path: '/admin/posts/:id', summary: 'Update post' },
      { method: 'DELETE', path: '/admin/posts/:id', summary: 'Delete post' },
      { method: 'POST', path: '/admin/posts/:id/publish', summary: 'Publish' },
      { method: 'POST', path: '/admin/posts/:id/unpublish', summary: 'Unpublish' },
      { method: 'POST', path: '/admin/posts/:id/feature', summary: 'Feature post' },
      { method: 'POST', path: '/admin/posts/:id/archive', summary: 'Archive post' },
      { method: 'GET', path: '/admin/posts/:id/revisions', summary: 'Revision history' },
      { method: 'GET', path: '/admin/comments', summary: 'List comments' },
      { method: 'GET', path: '/admin/comments/pending', summary: 'Pending moderation' },
      { method: 'GET', path: '/admin/comments/reported', summary: 'Reported comments' },
      { method: 'PATCH', path: '/admin/comments/:id/approve', summary: 'Approve comment' },
      { method: 'GET', path: '/admin/blog/analytics', summary: 'Blog analytics' },
      { method: 'GET', path: '/admin/blog/authors', summary: 'Authors list' },
    ],
  },
  {
    id: 'portfolio',
    title: 'Portfolio',
    description: 'Showcase work items for the public site.',
    endpoints: [
      { method: 'GET', path: '/admin/portfolio', summary: 'List items' },
      { method: 'POST', path: '/admin/portfolio', summary: 'Create item' },
      { method: 'GET', path: '/admin/portfolio/:id', summary: 'Item detail' },
      { method: 'PATCH', path: '/admin/portfolio/:id', summary: 'Update item' },
      { method: 'GET', path: '/admin/portfolio/:id/media', summary: 'List preview media' },
      { method: 'POST', path: '/admin/portfolio/:id/media/upload', summary: 'Upload preview file' },
      {
        method: 'DELETE',
        path: '/admin/portfolio/:id/media/:mediaId',
        summary: 'Remove preview file',
      },
      { method: 'DELETE', path: '/admin/portfolio/:id', summary: 'Delete item' },
      { method: 'POST', path: '/admin/portfolio/:id/publish', summary: 'Publish' },
      { method: 'POST', path: '/admin/portfolio/:id/unpublish', summary: 'Unpublish' },
    ],
  },
  {
    id: 'media',
    title: 'Media',
    description: 'Cloud storage browser — public/private buckets, user folders, selective sync.',
    endpoints: [
      { method: 'GET', path: '/admin/media/browse', summary: 'Folder tree (metadata only)' },
      { method: 'GET', path: '/admin/media', summary: 'List files (includeUrls=false by default)' },
      { method: 'GET', path: '/admin/media/users/:userId', summary: 'List user media' },
      { method: 'POST', path: '/admin/media/bulk-delete', summary: 'Bulk delete files' },
      {
        method: 'POST',
        path: '/admin/media/cleanup',
        summary: 'Run orphan cleanup (dryRun query)',
      },
      { method: 'GET', path: '/admin/media/:id', summary: 'File detail' },
      { method: 'GET', path: '/admin/media/:id/references', summary: 'Reference usage' },
      { method: 'GET', path: '/admin/media/:id/shares', summary: 'Share links' },
      { method: 'PATCH', path: '/admin/media/:id', summary: 'Update metadata' },
      { method: 'POST', path: '/admin/media/:id/replace', summary: 'Replace file contents' },
      { method: 'DELETE', path: '/admin/media/:id', summary: 'Delete file (force query)' },
      { method: 'GET', path: '/admin/media/:id/download', summary: 'Download URL' },
      { method: 'POST', path: '/admin/media/:id/reprocess', summary: 'Reprocess file' },
      { method: 'GET', path: '/admin/media/quarantine', summary: 'Quarantined files' },
      {
        method: 'POST',
        path: '/admin/media/quarantine/:id/release',
        summary: 'Release from quarantine',
      },
      { method: 'DELETE', path: '/admin/media/quarantine/:id', summary: 'Delete quarantined file' },
      { method: 'GET', path: '/admin/media/analytics', summary: 'Storage analytics' },
      { method: 'GET', path: '/admin/media/storage-usage', summary: 'Storage usage summary' },
      { method: 'PATCH', path: '/admin/media/settings', summary: 'Update media settings' },
    ],
  },
  {
    id: 'system',
    title: 'System',
    description: 'Configuration, feature flags, jobs, email templates, webhooks.',
    endpoints: [
      { method: 'GET', path: '/admin/system/config', summary: 'Read config' },
      { method: 'PATCH', path: '/admin/system/config', summary: 'Update config' },
      { method: 'GET', path: '/admin/system/features', summary: 'Feature flags' },
      { method: 'PATCH', path: '/admin/system/features/:flag', summary: 'Toggle feature' },
      { method: 'GET', path: '/admin/system/jobs', summary: 'Background jobs' },
      { method: 'POST', path: '/admin/system/jobs/:id/retry', summary: 'Retry job' },
      { method: 'DELETE', path: '/admin/system/jobs/:id', summary: 'Cancel job' },
      { method: 'GET', path: '/admin/system/email-templates', summary: 'Email templates' },
      { method: 'GET', path: '/admin/logs', summary: 'Auth audit logs' },
      { method: 'GET', path: '/admin/logs/security-stats', summary: 'Security statistics' },
      { method: 'GET', path: '/admin/webhooks', summary: 'List webhooks' },
      { method: 'POST', path: '/admin/webhooks', summary: 'Create webhook' },
      { method: 'GET', path: '/admin/webhooks/health', summary: 'Webhook health' },
      { method: 'GET', path: '/admin/notifications/templates', summary: 'Notification templates' },
    ],
  },
];

/** Flat count for display */
export function countAdminEndpoints(): number {
  return ADMIN_ENDPOINT_GROUPS.reduce((n, g) => n + g.endpoints.length, 0);
}
