export const adminKeys = {
  root: ['admin'] as const,
  overview: () => [...adminKeys.root, 'dashboard', 'overview'] as const,
  revenue: () => [...adminKeys.root, 'dashboard', 'revenue'] as const,
  activity: () => [...adminKeys.root, 'dashboard', 'activity'] as const,
  alerts: () => [...adminKeys.root, 'dashboard', 'alerts'] as const,
  users: () => [...adminKeys.root, 'users'] as const,
  user: (id: string) => [...adminKeys.root, 'user', id] as const,
  projectsStats: () => [...adminKeys.root, 'projects', 'stats'] as const,
  payments: () => [...adminKeys.root, 'payments', 'list'] as const,
  payment: (id: string) => [...adminKeys.root, 'payments', 'detail', id] as const,
  milestones: () => [...adminKeys.root, 'payments', 'milestones'] as const,
  reconciliation: (params?: Record<string, string | number | boolean | undefined>) =>
    [...adminKeys.root, 'payments', 'reconciliation', params ?? {}] as const,
  systemConfig: () => [...adminKeys.root, 'system', 'config'] as const,
  systemFeatures: () => [...adminKeys.root, 'system', 'features'] as const,
  systemJobs: () => [...adminKeys.root, 'system', 'jobs'] as const,
  emailTemplates: () => [...adminKeys.root, 'system', 'email-templates'] as const,
  health: () => [...adminKeys.root, 'health'] as const,
  posts: () => [...adminKeys.root, 'posts'] as const,
  postAnalytics: () => [...adminKeys.root, 'posts', 'analytics'] as const,
  comments: () => [...adminKeys.root, 'comments'] as const,
  pendingComments: () => [...adminKeys.root, 'comments', 'pending'] as const,
  reportedComments: () => [...adminKeys.root, 'comments', 'reported'] as const,
  contact: () => [...adminKeys.root, 'contact'] as const,
  requests: () => [...adminKeys.root, 'requests'] as const,
  request: (id: string) => [...adminKeys.root, 'request', id] as const,
  requestStats: () => [...adminKeys.root, 'requests', 'stats'] as const,
  quotes: () => [...adminKeys.root, 'quotes'] as const,
  quote: (id: string) => [...adminKeys.root, 'quote', id] as const,
  quoteStats: () => [...adminKeys.root, 'quotes', 'stats'] as const,
  lineItemLibrary: () => [...adminKeys.root, 'quotes', 'line-item-library'] as const,
  paymentSchedulePresets: () => [...adminKeys.root, 'quotes', 'payment-schedule-presets'] as const,
  capacityDashboard: () => [...adminKeys.root, 'requests', 'capacity'] as const,
  timeEntries: (projectId?: string) =>
    projectId
      ? ([...adminKeys.root, 'time-entries', projectId] as const)
      : ([...adminKeys.root, 'time-entries'] as const),
  revenueReport: () => [...adminKeys.root, 'payments', 'revenue-report'] as const,
  blogCategories: () => [...adminKeys.root, 'blog', 'categories'] as const,
  blogTags: () => [...adminKeys.root, 'blog', 'tags'] as const,
  blogAuthors: () => [...adminKeys.root, 'blog', 'authors'] as const,
  flaggedMessages: () => [...adminKeys.root, 'messages', 'flagged'] as const,
  moderationHistory: () => [...adminKeys.root, 'messages', 'moderation-history'] as const,
  webhooks: () => [...adminKeys.root, 'webhooks'] as const,
  webhookMeta: () => [...adminKeys.root, 'webhooks', 'meta'] as const,
  auditLogs: () => [...adminKeys.root, 'logs'] as const,
  securityStats: () => [...adminKeys.root, 'logs', 'security-stats'] as const,
  usersLogs: () => [...adminKeys.root, 'users', 'logs'] as const,
  portfolio: () => [...adminKeys.root, 'portfolio'] as const,
  portfolioItem: (id: string) => [...adminKeys.root, 'portfolio', id] as const,
  impersonationSessions: () => [...adminKeys.root, 'impersonation', 'sessions'] as const,
  pipelineUser: (userId: string) => [...adminKeys.root, 'pipeline', 'user', userId] as const,
  pipelineProject: (projectId: string) =>
    [...adminKeys.root, 'pipeline', 'project', projectId] as const,
};
